language: ruby
rvm:
  - 1.8.7
before_script:
  - 'git clone git://github.com/saz/puppet-ssh spec/fixtures/modules/ssh'
  - 'git clone git://github.com/puppetlabs/puppetlabs-rsync spec/fixtures/modules/rsync'
  - 'git clone git://github.com/ghoneycutt/puppet-xinetd spec/fixtures/modules/xinetd'
  - 'git clone git://github.com/saz/puppet-memcached spec/fixtures/modules/memcached'
  - 'git clone git://github.com/puppetlabs/puppetlabs-stdlib spec/fixtures/modules/stdlib'
  - 'git clone git://github.com/puppetlabs/puppet-apt spec/fixtures/modules/apt'
  - 'git clone git://github.com/puppetlabs/puppetlabs-keystone spec/fixtures/modules/keystone'
  - 'git clone git://github.com/ripienaar/puppet-concat spec/fixtures/modules/concat'
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.6.9
notifications:
  email: false
